run:
  timeout: 5m

  skip-dirs:
    - internal
    - pkg/registry

linters:
  enable:
  - asciicheck
  - deadcode
  - depguard
  - errorlint
  - gofmt
  - goimports
  - importas
  - prealloc
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - whitespace

  disable:
  - errcheck
