version: "2"
linters:
  enable:
    - asciicheck
    - depguard
    - errorlint
    - gosec
    - importas
    - misspell
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  disable:
    - errcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: crypto/sha256
              desc: use crypto.SHA256 instead
    gosec:
      excludes:
        - G117 # Exported sensitive fields
        - G703 # Path taint (from arguments)
        - G704 # SSRF taint (raised when constructing URLs)
        - G706 # Log taint (from arguments)
    revive:
      enable-default-rules: true
      rules:
        - name: var-naming
          arguments:
          - []
          - []
          - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: test # Excludes /test, *_test.go etc.
    paths:
      - internal
      - pkg/registry
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal
      - pkg/registry
      - third_party$
      - builtin$
      - examples$
