run:
  timeout: 5m

issues:
  exclude-dirs:
    - internal
    - pkg/registry
    - pkg/v1/daemon
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec

linters:
  enable:
  - asciicheck
  - depguard
  - errorlint
  - gofmt
  - gosec
  - goimports
  - importas
  - prealloc
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - unused
  - whitespace

  disable:
  - errcheck

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "crypto/sha256"
            desc: use crypto.SHA256 instead
