run:
  timeout: 5m

  skip-dirs:
    - internal
    - pkg/registry

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec

linters:
  enable:
  - asciicheck
  - depguard
  - errorlint
  - gofmt
  - gosec
  - goimports
  - importas
  - prealloc
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - unused
  - whitespace

  disable:
  - errcheck

linters-settings:
  depguard:
    include-go-root: true
    packages-with-error-message:
    - crypto/sha256: "use crypto.SHA256 instead"
