# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - go mod download
#     # you may remove this if you don't need go generate
#     - go generate ./...
builds:
- id: crane
  env:
  - CGO_ENABLED=0
  main: ./cmd/crane/main.go
  binary: crane
  flags:
  - -trimpath
  ldflags:
    - -s
    - -w
    - -X github.com/google/go-containerregistry/cmd/crane/cmd.Version={{.Version}}
    - -X github.com/google/go-containerregistry/pkg/v1/remote/transport.Version={{.Version}}
  goarch:
    - amd64
    - arm
    - arm64
    - 386
    - s390x
    - ppc64le
  goos:
    - linux
    - darwin
    - windows
  ignore:
    - goos: windows
      goarch: 386

- id: gcrane
  env:
  - CGO_ENABLED=0
  main: ./cmd/gcrane/main.go
  binary: gcrane
  flags:
  - -trimpath
  ldflags:
    - -s
    - -w
    - -X github.com/google/go-containerregistry/cmd/crane/cmd.Version={{.Version}}
    - -X github.com/google/go-containerregistry/pkg/v1/remote/transport.Version={{.Version}}
  goarch:
    - amd64
    - arm
    - arm64
    - 386
    - s390x
    - ppc64le
  goos:
    - linux
    - darwin
    - windows
  ignore:
    - goos: windows
      goarch: 386

- id: krane
  env:
  - CGO_ENABLED=0
  main: ./main.go
  dir: ./cmd/krane
  binary: krane
  flags:
  - -trimpath
  ldflags:
    - -s
    - -w
    - -X github.com/google/go-containerregistry/cmd/crane/cmd.Version={{.Version}}
    - -X github.com/google/go-containerregistry/pkg/v1/remote/transport.Version={{.Version}}
  goarch:
    - amd64
    - arm
    - arm64
    - 386
    - s390x
    - ppc64le
  goos:
    - linux
    - darwin
    - windows
  ignore:
    - goos: windows
      goarch: 386
source:
  enabled: true
archives:
- name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  footer: |
    ### Container Images

    https://ghcr.io/google/go-containerregistry/crane:{{.Tag}}
    https://ghcr.io/google/go-containerregistry/gcrane:{{.Tag}}

    For example:
    ```
    docker pull ghcr.io/google/go-containerregistry/crane:{{.Tag}}
    docker pull ghcr.io/google/go-containerregistry/gcrane:{{.Tag}}
    ```
