steps:
# Build the ko binary.
- name: gcr.io/cloud-builders/go:debian
  env: ['PROJECT_ROOT=github.com/google/go-containerregistry']
  args: ['get', 'github.com/google/ko/cmd/ko']

# Use the ko binary to build the crane and gcrane builder images, tagging them with "latest" and this commit.
- name: gcr.io/cloud-builders/go:debian
  env: ['GOPATH=/workspace/gopath', 'KO_DOCKER_REPO=gcr.io/$PROJECT_ID']
  entrypoint: /workspace/gopath/bin/ko
  dir: gopath/src
  args: ['publish', '-B', 'github.com/google/go-containerregistry/cmd/crane', '-t', 'latest', '-t', '$COMMIT_SHA']

- name: gcr.io/cloud-builders/go:debian
  env: ['GOPATH=/workspace/gopath', 'KO_DOCKER_REPO=gcr.io/$PROJECT_ID']
  entrypoint: /workspace/gopath/bin/ko
  dir: gopath/src
  args: ['publish', '-B', 'github.com/google/go-containerregistry/cmd/gcrane', '-t', 'latest', '-t', '$COMMIT_SHA']

# Use the crane builder to get the digest for crane and gcrane.
- name: gcr.io/$PROJECT_ID/crane
  args: ['digest', 'gcr.io/$PROJECT_ID/crane']

- name: gcr.io/$PROJECT_ID/crane
  args: ['digest', 'gcr.io/$PROJECT_ID/gcrane']
