FROM python:3.7.4-buster

RUN head -c 50MB /dev/urandom > /0.txt
RUN head -c 50MB /dev/urandom > /1.txt
RUN head -c 50MB /dev/urandom > /2.txt
RUN head -c 50MB /dev/urandom > /3.txt
RUN head -c 50MB /dev/urandom > /4.txt
RUN head -c 50MB /dev/urandom > /5.txt
RUN head -c 50MB /dev/urandom > /6.txt
RUN head -c 50MB /dev/urandom > /7.txt
RUN head -c 50MB /dev/urandom > /8.txt
RUN head -c 50MB /dev/urandom > /9.txt
