name: Boilerplate

on:
  pull_request:
    branches: ['main']

jobs:

  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        extension:
        - go
        - sh

        # Map between extension and human-readable name.
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: chainguard-dev/actions/boilerplate@29fb6e979a0b3efc79748a17e8cec08d0594cbfd # main
        with:
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
