name: Build

on:
  pull_request:
    branches: ['main']

env:
  GOTOOLCHAIN: local

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: '.go-version'

      - run: |
          go build ./...
          go test -run=^$ ./...
