name: Build

on:
  pull_request:
    branches: ['main']

env:
  GOTOOLCHAIN: local

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: '.go-version'

      - run: |
          go build ./...
          go test -run=^$ ./...
