name: Do Not Submit

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        persist-credentials: false
    - uses: chainguard-dev/actions/donotsubmit@0ffab11a71c1b7bd68ddf94665a8ec88b116223d # v1.6.33
