name: Do Not Submit

on:
  pull_request:
    branches: ['main']

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/actions/donotsubmit@04b3d27d680c065e8aaaa71edabf37da0ad4ac3d # main
