name: Basic e2e test

on:
  pull_request: 
    branches: ['main']

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - windows-latest
    name: e2e ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: crane append to an image, set the entrypoint, run it locally, roundtrip it
      shell: bash
      run: |
        set -euxo pipefail

        # Setup local registry
        go run ./cmd/registry &

        base=alpine
        platform=linux/amd64
        if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
          base=mcr.microsoft.com/windows/nanoserver:1809
          platform=windows/amd64
        fi

        CGO_ENABLED=0 go build -o app/crane ./cmd/crane
        tar cvf crane.tar app

        # This prevents Bash for Windows from mangling path names.
        # It shouldn't be necessary in general unless you're using Bash for
        # Windows.
        export MSYS_NO_PATHCONV=1

        img=$(./app/crane mutate \
            --entrypoint=/app/crane,version \
            $(./app/crane append \
                --platform ${platform} \
                --base ${base} \
                --new_tag localhost:1338/append-test \
                --new_layer crane.tar))

        # Run the image with and without args.
        docker run $img 
        docker run $img --help

        # Make sure we can roundtrip it through pull/push
        layout=$(mktemp -d)
        dst=localhost:1338/roundtrip-test

        ./app/crane pull --format=oci $img $layout
        ./app/crane push --image-refs=foo.images $layout $dst
        diff <(./app/crane manifest $img) <(./app/crane manifest $(cat foo.images))
