name: Basic e2e test

on:
  pull_request: 
    branches: ['main']

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - windows-latest
    name: e2e ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Use crane to append an image and write it to the local Docker daemon
      shell: bash
      run: |
        set -euxo pipefail

        base=alpine
        platform=linux/amd64
        if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
          base=mcr.microsoft.com/windows/nanoserver:1809
          platform=windows/amd64
        fi

        go run ./cmd/crane append \
            --platform ${platform} \
            --base ${base} \
            --new_tag append-test \
            --new_layer pkg/v1/tarball/testdata/content.tar \
            --daemon

        docker inspect append-test
