name: Push image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  push-image:
    name: Push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        go build ./cmd/crane
        echo ${GITHUB_TOKEN} | ./crane auth login ghcr.io --username unused --password-stdin
        ./crane cp gcr.io/distroless/static:nonroot ghcr.io/${{ github.repository }}/testimage
