name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

env:
  GOTOOLCHAIN: local

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: '.go-version'

      - run: go test -coverprofile=coverage.txt -covermode=atomic -race ./...

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
